services:
  mongodb:
    container_name: nodejs
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodejs
      MONGO_INITDB_ROOT_PASSWORD: secret123456
    ports:
      - 27017:27017